# on: [push]

# jobs:
#     build-and-publish:
#       runs-on: ubuntu-latest
#       name: My workflow
#       steps:
#         - name: Execute Action Graph
#           uses: actionforge/action@b350d491aef4ae17ac4f5270a2fc5186be0f39db  # v0.9.42
#           with:
#             graph_file: workflow-ci.yml
on: push

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan code for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Adjust this to the Python version you need for your project

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Build
        run: |
          poetry install
          poetry build
