# on: [push]

# jobs:
#     build-and-publish:
#       runs-on: ubuntu-latest
#       name: My workflow
#       steps:
#         - name: Execute Action Graph
#           uses: actionforge/action@b350d491aef4ae17ac4f5270a2fc5186be0f39db  # v0.9.42
#           with:
#             graph_file: workflow-ci.yml
on: push

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan code for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12" # Adjust to the Python version required by your project

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install pyzmq with pip as a workaround
        run: pip install pyzmq==24.0.1

      - name: Build
        run: |
          poetry install
          poetry build
